image: node:lts-buster

pipelines:
  default:
    - parallel:
        - step:
            name: Mirror to GitHub
            script:
              - git fetch
              - git pull
              - git push --mirror git@github.com:HoloRes/suisei-bot.git

        - step:
            name: Code linting
            script:
              - npm install
              - npm run lint:ci
            caches:
              - node

        - step:
            name: Scan using Snyk
            script:
              - npm install -g snyk # binary download also available
              - npm ci
              - pipe: snyk/snyk-scan:0.4.6
                variables:
                  SNYK_TOKEN: $SNYK_TOKEN
                  LANGUAGE: "npm"
                  CODE_INSIGHTS_RESULTS: "true"
                  MONITOR: "true"
                  DONT_BREAK_BUILD: "true"
            caches:
              - node

        - step:
            name: Build
            script:
              - IMAGE_NAME=$BITBUCKET_REPO_SLUG
              - REPO_URL=$BITBUCKET_GIT_HTTP_ORIGIN
              - docker build . --file Dockerfile --tag ${IMAGE_NAME}
                --label "org.opencontainers.image.url"="${REPO_URL}"
                --label "org.opencontainers.image.source"="${REPO_URL}"
                --label "org.opencontainers.image.title"="${BITBUCKET_REPO_SLUG}"
                --label "org.opencontainers.image.licenses"="MIT"
                --label "org.opencontainers.image.description"="A Discord bot specifically built for VTuber servers"
                --label "org.opencontainers.image.revision"="${BITBUCKET_COMMIT}"
                --label "org.opencontainers.image.version"="${BITBUCKET_BRANCH}"
              - docker save ${IMAGE_NAME} --output "${IMAGE_NAME}.tar"
            services:
              - docker
            caches:
              - docker
            artifacts:
              - "*.tar"

        - step:
            name: Lint the Dockerfile
            image: hadolint/hadolint:latest-debian
            script:
              - hadolint Dockerfile

    - step:
        name: Push to GHCR
        script:
          - IMAGE_NAME=$BITBUCKET_REPO_SLUG
          - docker load --input "${IMAGE_NAME}.tar"
          - echo ${DOCKER_PASSWORD} | docker login ghcr.io --username "$DOCKER_USERNAME" --password-stdin
          - VERSION=$(echo $BITBUCKET_COMMIT | cut -c1-7)
          - IMAGE=ghcr.io/${DOCKER_NAMESPACE}/${IMAGE_NAME}
          - docker tag "${IMAGE_NAME}" "${IMAGE}:${VERSION}"
          - docker push "${IMAGE}:${VERSION}"
        services:
          - docker


  pull-requests:
    master:
      - step:
          name: Create Sentry release
          script:
            - pipe: holores/sentry-new-release:0.4.0
              variables:
                SENTRY_AUTH_TOKEN: $SENTRY_TOKEN
                SENTRY_ORG: $SENTRY_ORG
                SENTRY_URL: $SENTRY_URL
                SENTRY_PROJECT: $SENTRY_PROJECT
                ENVIRONMENT: 'staging'

      - step:
          name: Deploy to Staging
          deployment: Staging
          script:
            # Install Python
            - apt update -y
            - sudo apt install -y python3-pip
            # Create and push Docker image
            - echo ${DOCKER_PASSWORD} | docker login ghcr.io --username "$DOCKER_USERNAME" --password-stdin
            - IMAGE_NAME=$BITBUCKET_REPO_SLUG
            - docker load --input "${IMAGE_NAME}.tar"
            - ENVIRONMENT="staging"
            - IMAGE=ghcr.io/${DOCKER_NAMESPACE}/${IMAGE_NAME}
            - docker tag "${IMAGE_NAME}" "${IMAGE}:${ENVIRONMENT}"
            - docker push "${IMAGE}:${ENVIRONMENT}"
            # Call Ansible
            - ./.bitbucket/tower.bash staging "$VERSION"

          services:
            - docker

  branches:
    master:
      - step:
          script:
            - VERSION=$(echo $BITBUCKET_COMMIT | cut -c1-7)
            - IMAGE=ghcr.io/${DOCKERHUB_NAMESPACE}/${IMAGE_NAME}
            - pipe: anchore/anchore-scan:0.2.14
              variables:
                IMAGE_NAME: "${IMAGE}:${VERSION}"

      - step:
          name: Create Sentry release
          script:
            - pipe: holores/sentry-new-release:0.4.0
              variables:
                SENTRY_AUTH_TOKEN: $SENTRY_TOKEN
                SENTRY_ORG: $SENTRY_ORG
                SENTRY_URL: $SENTRY_URL
                SENTRY_PROJECT: $SENTRY_PROJECT
                ENVIRONMENT: 'production'

      - step:
          name: Deploy to Production
          deployment: Production
          script:
            # Install Python
            - apt update -y
            - sudo apt install -y python3-pip
            # Create and push Docker image
            - echo ${DOCKER_PASSWORD} | docker login ghcr.io --username "$DOCKER_USERNAME" --password-stdin
            - IMAGE_NAME=$BITBUCKET_REPO_SLUG
            - docker load --input "${IMAGE_NAME}.tar"
            - ENVIRONMENT="prod"
            - IMAGE=ghcr.io/${DOCKER_NAMESPACE}/${IMAGE_NAME}
            - docker tag "${IMAGE_NAME}" "${IMAGE}:${ENVIRONMENT}"
            - docker push "${IMAGE}:${ENVIRONMENT}"
            # Call Ansible
            - ./.bitbucket/tower.bash production "$VERSION"
          services:
            - docker