version: '3'

services:
#  database:
#    image: cockroachdb/cockroach
#    command: start-single-node --insecure
#    ports:
#      - "26257:26257"
#      - "28080:8080"
#    volumes:
#      - db:/cockroach/cockroach-data

  redis:
    image: redis
    command: redis-server --save 60 1
    ports:
      - "6380:6379"
    volumes:
      - redis:/data

  meilisearch:
    image: getmeili/meilisearch
    command: meilisearch --env="development"
    environment:
      - "MEILI_MASTER_KEY=MASTER_KEY"
    ports:
      - "7700:7700"
    volumes:
      - meilisearch:/meili_data

volumes:
  db:
  redis:
  meilisearch:
