version: '3'

services:
  database:
    image: cockroachdb/cockroach:v22.1.6
    command: start --insecure
    ports:
      - "26257:26257"
      - "28080:8080"
    volumes:
      - db:/cockroach/cockroach-data

  redis:
    image: redis:7
    command: redis-server --save 60 1
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  meilisearch:
    image: getmeili/meilisearch:v0.28
    command: meilisearch --env="development"
    environment:
      - "MEILI_MASTER_KEY=MASTER_KEY"
    ports:
      - "7700:7700"
    volumes:
      - meilisearch:/meili_data

volumes:
  db:
  redis:
  meilisearch:
