apiVersion: v1
kind: Namespace
metadata:
  name: suisei-mic
spec: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: suisei-mic
  name: suisei-mic
  namespace: suisei-mic
spec:
  replicas: 1
  selector:
    matchLabels:
      run: suisei-mic
  template:
    metadata:
      labels:
        run: suisei-mic
        app: suisei-mic
    spec:
      containers:
        - image: ghcr.io/holores/suisei-bot:{{version}}
          name: suisei-mic
          volumeMounts:
            - mountPath: /app/config.js
              name: suisei-config
              subPath: config.js
      volumes:
        - name: suisei-config
          configMap:
            name: suisei-config-file

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: suisei-mic
  name: suisei-mic
  namespace: suisei-mic
spec:
  ports:
    - port: 80
  selector:
    app: suisei-mic

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: suisei-mic-metrics
  name: suisei-mic-metrics
  namespace: suisei-mic
spec:
  ports:
    - port: 5000
  selector:
    app: suisei-mic
